### ISSUE TITLE
Raw mode

### ISSUE THREAD

**Issue by nikipore** [blairvanderhoof/gist-embed#15]
It would be great if `gist-embed` had a raw mode which would respect the existing options (as far as they make sense) but deliver unformatted text (mode=raw), or a table with two columns for line numbers and code (mode=table).

This way one could pull in gists and format them oneself. It would also open the possibility of adding `noscript` tags in static HTML engines containing the gist.

**Comment by blairvanderhoof** [comment]
Feel free to open a pull request for these. Closing for now.
