### ISSUE TITLE
remove loading text

### ISSUE THREAD

**Issue by timothyerwin** [blairvanderhoof/gist-embed#35]
great library! just one request...can you remove this code, or at least make it optional?

```javascript
// loading
$elem.html('Loading gist ' + url + (data.file ? ', file: ' + data.file : '') + '...');
````

**Comment by blairvanderhoof** [comment]
Thanks @timothyerwin. What was the reasoning for wanting to remove the loading text?  I can pass an optional attribute in to disable the loading text.  I would still like to leave the error messaging though in case the gist fails to load.

**Comment by timothyerwin** [comment]
yes, it shows up like a blip. it's so quick it's pointless and from my perspective it looks bad on the ui. I would prefer the gists just load like github designed them.

if an error happens then by all means display the error. I think the best idea would be to set some callbacks so the user can decide what to do when loading/error.

**Comment by blairvanderhoof** [comment]
Just implemented this.  Upgrade to the v2.1 and use data-gist-show-loading="false" to prevent the loading text from showing.

**Comment by timothyerwin** [comment]
works great. thanks!
