### ISSUE TITLE
Add support for Internalization

### ISSUE THREAD

**Issue by shivapoudel** [blairvanderhoof/gist-embed#37]
Is there any way we can translate `Loading` and `Failed` message for our convenient ;)

**Comment by blairvanderhoof** [comment]
Great idea.  How would you like the API to be?  Something like this?

```
  <script src="gist-embed.js/>
  <script>
   GistEmbed.strings.loading = 'My Loading String';
   GistEmbed.strings.failed = 'My failed String';
  </script>
```

For now you can disable the loading text: https://gist.github.com/blairvanderhoof/f847e6866e13ed607f49#file-example-html

**Comment by shivapoudel** [comment]
```
  <script>
   GistEmbed.strings.loading = 'My Loading String';
   GistEmbed.strings.failed = 'My failed String';
  </script>
```
Will be alright

**Comment by shivapoudel** [comment]
Rather than this, the great option will be to add the loader just like of github so we don't need to localized too :)

Or rather enhanced the loader to use with jquery-blockUI

**Comment by shivapoudel** [comment]
Can't we additionally use this knid of loader:
![capture](https://cloud.githubusercontent.com/assets/3774827/8866352/0ee84e9e-31db-11e5-9412-312530f12100.PNG)

**Comment by blairvanderhoof** [comment]
That's a great idea, would you like to submit a pull request?
