### ISSUE TITLE
Feature request line highlight color

### ISSUE THREAD

**Issue by shivapoudel** [blairvanderhoof/gist-embed#38]
Add custom support for custom line highlight or selection color. This can be set from the html data :tada:

**Comment by luanmuniz** [comment]
We have that feature:
https://github.com/blairvanderhoof/gist-embed#how-do-i-highlight-line-numbers

**Comment by shivapoudel** [comment]
@luanmuniz I am talking about color for that highlight line :)

**Comment by shivapoudel** [comment]
IMO this can be change through with some style in our own styles :)
