### ISSUE TITLE
Line number issue

### ISSUE THREAD

**Issue by shivapoudel** [blairvanderhoof/gist-embed#41]
Using v2.2
![capture](https://cloud.githubusercontent.com/assets/3774827/8864409/5320d8b6-31c1-11e5-89e9-059daaeab39c.PNG)

**Comment by blairvanderhoof** [comment]
Does this help? https://github.com/blairvanderhoof/gist-embed#why-does-my-gist-embed-have-incorrect-styling

http://blairvanderhoof.com/gist-embed/ examples load just fine.

**Comment by shivapoudel** [comment]
Thanks, this was cause by below styles already applied into my theme:
```
table {
	table-layout: fixed;
	width: 100%;
}
```

**Comment by blairvanderhoof** [comment]
Great I'm glad you were able to fix it.
