### ISSUE TITLE
data-gist-line doesn't appear to be working

### ISSUE THREAD

**Issue by matt-bailey** [blairvanderhoof/gist-embed#43]
We've had the `git-embed` plugin on our site for quite a while now and haven't had any problems. However, yesterday someone pointed out that all the gists are showing in their entirety, i.e. `data-gist-line` doesn't appear to be working.

Our embeds look like this:

```html
<div style="display: block;" data-gist-file="misc.txt" data-gist-id="8320826" data-gist-line="2">
```

You can see in the screen shot below that the whole gist is displaying, rather than an individual line. There are no errors in the console.

![screenshot 2015-08-18 10 01 47](https://cloud.githubusercontent.com/assets/969385/9326267/7e35402c-4590-11e5-9825-910a2fd268f0.png)

As I said, this was all working fine in the past although I'm not sure at what point it stopped working as it was only pointed out to me yesterday.

Thanks.

**Comment by blairvanderhoof** [comment]
Please upgrade to the latest version 2.2, there was a breaking change in githubs gist api https://github.com/blairvanderhoof/gist-embed#version-22-july-20-2015
http://blairvanderhoof.com/gist-embed/ is using the latest versions and shows the line number removal technique correctly.

**Comment by matt-bailey** [comment]
Thanks, that fixed it :)
