### ISSUE TITLE
HTTP 429 too many requests

### ISSUE THREAD

**Issue by daniellevass** [blairvanderhoof/gist-embed#44]
Hi,

Probably not a gist-embed problem; but we're experiencing a lot of HTTP 429 requests (too many requests) recently. Has anyone else experienced this? Is there any information on the number of gist requests per minute/hour we can use?

Thank you,

Danielle.

**Comment by blairvanderhoof** [comment]
Hi @daniellevass, have you tried contacting github support on this?

**Comment by blairvanderhoof** [comment]
Can't repro. Closing.
