### ISSUE TITLE
Can't see the gist text

### ISSUE THREAD

**Issue by StephanKrauss** [blairvanderhoof/gist-embed#52]
Hello,

i have test the combination of my blog and the gist-embed.js.
Unfortunately i can't see the text of my gist.
See: https://t.co/8W41oqzeq9

Your sincerly

Stephan

**Comment by blairvanderhoof** [comment]
Hi did you check http://blairvanderhoof.com/gist-embed/ for examples of usage? Try doing a view source on the page to see the markup and script includes.

**Comment by blairvanderhoof** [comment]
I am able to see your gist embeds on my mobile phone.

**Comment by StephanKrauss** [comment]
Hello,

thanks for the quick answer.
Please test the following URL.
http://www.stephankrauss.de

Your sincerly

Stephan

**Comment by blairvanderhoof** [comment]
Looks fine to me.
