### ISSUE TITLE
How can we chnage the content within gist-meta?

### ISSUE THREAD

**Issue by NaseebullahSafi** [blairvanderhoof/gist-embed#54]
I really love what you did, however I might be missing something, how can I change the gist-meta content to something else?

**Comment by blairvanderhoof** [comment]
Can you explain more, maybe a code snippet, what you are trying to do? I'm not sure what 'gist-meta' is.

**Comment by Developer4Life** [comment]
So currently, the script that you have provided is working, the gist syntax highlighter is visible. However I need to change some of the content within the html in the embed code.

How can I do that?

![image](https://cloud.githubusercontent.com/assets/16179773/17003480/18ea37e4-4ec8-11e6-9ec4-54c6a6ab942b.png)

**Comment by blairvanderhoof** [comment]
Currently you can only hide the footer. What do you want to change in the footer exactly?

**Comment by Developer4Life** [comment]
I want to change the name "github" to my name in the footer

**Comment by blairvanderhoof** [comment]
I'd have to add support for that or you can put up a diff to add a new attribute, gist-embed-footer-name="Your Name" and replace the last anchor tag content in gist-meta with that value.
