### ISSUE TITLE
Support gist-embed with medium.com

### ISSUE THREAD

**Issue by siddharthlatest** [blairvanderhoof/gist-embed#57]
I would like to use gist-embed within medium blogs for line highlighting gist files. Medium has a way for adding embeds via embedly - can `gist-embed` be a provider?

Are there other alternatives for including a `gist-embed` within medium?

**Comment by blairvanderhoof** [comment]
Does this work @siddharthlatest https://blog.medium.com/yes-we-get-the-gist-1c2a27cdfc22?
