### ISSUE TITLE
Collapsable code viewer

### ISSUE THREAD

**Issue by aplocher** [blairvanderhoof/gist-embed#58]
Is there a simple way to make the embedded code have a max-height of, say, 300px otherwise show scrollbars?  I would like to embed a couple hundred lines of code in the middle of a blog post, but I don't want it to be the main focus of the blog post.

Ideally with the footer fixed at the bottom (or have this be an option). 

This can be accomplished with the normal embedded code from gist.github.com with the following CSS:

`div.gist { overflow:auto; max-height:300px; }`

However, it doesn't make the footer remain fixed.

EDIT: keeping the footer in place can be done by using the following CSS (instead of the CSS I suggested earlier):  

`.gist .blob-wrapper{max-height:350px;overflow-y:auto !important}`

**Comment by aplocher** [comment]
An optional expand/maximize button would be great too (when it's collapsed)

**Comment by blairvanderhoof** [comment]
looks like you can do:

`.gist .gist-data {  max-height: 300px; }`

It should scroll automatically.

Feel free to submit a diff to enable these features. Not sure when I can get to them. Thanks for the report.

**Comment by blairvanderhoof** [comment]
#60 fixed this
