### ISSUE TITLE
Entire gist, no scrolling

### ISSUE THREAD

**Issue by rodolfo-viana** [blairvanderhoof/gist-embed#69]
This is a great js. Thanks for working to make it better each day.

I don't know if you accept suggestions but I was wondering if it is possible to show every line on a gist (an entire gist) with no scrolling.

I submit tis idea because some websites, due to their contents, already have a scrollbar. By embedding gist these websites show two scrollbars and the navigation gets a little confusing.

**Comment by blairvanderhoof** [comment]
Feel free to submit a PR, sounds like a reasonable idea!
